#+begin_src emacs-lisp

  (defun github-readme ()
    "Personal README for Github.")

#+end_src

* Introduction

Hello, I'm Gabriel! I'm an aspiring software engineer currently enrolled in my state's federal university.

* Interests

** [[https://www.gnu.org/software/emacs/][Emacs]]

Emacs is not just a text editor, it's a full on application environment, with support for web browsing, e-mail, code editing...

I hope to contribute more to the community in the future. For now, I have a configuration that takes inspiration from many users of the community.

*** [[https://github.com/magit/magit][Magit]]

It's a great git interface for Emacs. This file was pushed to Github using it! It's maintained by [[https://github.com/tarsius][Jonas]], a prominent member of the community.

** [[https://orgmode.org/][Org Mode]]

This README was written using Org Mode! I used markdown before, but Org Mode is perfect for Emacs.

** [[https://guix.gnu.org/][GNU Guix]]

The GNU operating system! Using the store model, I don't even have to keep track of all the stuff I have installed, as I can remove anything not part of [[https://github.com/gs-101/.files][my configuration]] with a simple ~guix gc~.

Besides the quick disposal aspect with ~guix gc~, I can temporarily install software with ~guix shell~ and then go back to my previous environment with ~exit~.

But that's not even the best part! I can declaratively configure both my system and home environment with Scheme, so, combined with Emacs, I can always have a Lisp in hands.

** [[https://nixos.org/][NixOS]]

Guix's older sibling. I never used NixOS itself, and I don't plan to since I have Guix, but I use [[https://nix-community.github.io/home-manager/][home-manager]] with my Guix setup and its lovely. Whatever I can't find on Guix, I can find it in Nix and use it as a regular part of my system.

And if I can't find it, I can write a package for either of them.

* Links

#+html:<a href="https://wakatime.com/@c323cd78-020a-44af-acec-a4f362e322a5"><img src="https://wakatime.com/badge/user/c323cd78-020a-44af-acec-a4f362e322a5.svg" alt="Total time coded since Sep 7 2024" /></a>

#+html:<a href="https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xd1d337f6cb3202dcb9ba337bf9d8eabcf57eed58"><img src="https://img.shields.io/badge/_-GPG_Key_on_Ubuntu-822422?style=flat-square&logo=GNU&logoColor=black&labelColor=white">

#+html:<a href="https://keys.openpgp.org/vks/v1/by-fingerprint/D1D337F6CB3202DCB9BA337BF9D8EABCF57EED58"><img src="https://img.shields.io/badge/_-GPG_Key_on_OpenPGP-822422?style=flat-square&logo=GNU&logoColor=black&labelColor=white">
